import type { PropsWithChildren } from "react";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="ja">
            <body>{children}</body>
        </html>
    );
}
